field_separator: "\t"
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
user_inter_num_interval: "[20,inf)"
load_col:
    inter: [user_id, item_id, timestamp]
normalize_all: false

# Evaluation
eval_args:                            # (dict) 4 keys: group_by, order, split, and mode
  split: {'LK': ['valid_and_test', 5]}   # (dict) The splitting strategy ranging in ['RS','LS'].{'RS':[0.8,0.1,0.1]}, valid_and_test, test_only, valid_only
  #split: { 'RS':[0.7,0.1,0.2] }       # (dict) The splitting strategy ranging in ['RS','LS'].{'RS':[0.8,0.1,0.1]}
  group_by: user                      # (str) The grouping strategy ranging in ['user', 'none'].
  order: TO                           # (str) The ordering strategy ranging in ['RO', 'TO'].
  mode: full

save_step: 1
eval_step: 1
topUser: 10

# Training
shuffle: False
learner: adam                   # (str) The name of used optimizer.
show_progress: False
valid_metric: "ndcg@10"
train_neg_sample_args: ~

# best hyper parameters
knn_method: 'item'
alpha: 0.4
beta: 0.6
k: 60
q: 1